### ISSUE TITLE
gap/unset/unsure

### ISSUE THREAD

**Issue by annevk** [battre/autocomplete-attribute-explainer#3]
It looks like these are proposals for new tokens. Hopefully that's not actually the case? I suggest not using the same green background for these as the new tokens and perhaps categorizing them differently altogether.

**Comment by battre** [comment]
Thanks. I have fixed the rendering.

**Comment by annevk** [comment]
This is not entirely fixed.

One thing that was confusing to us was the Tokens column for `location-in-building` for instance, where it still says `gap` with a green background.

**Comment by battre** [comment]
Copy&paste error. This should be fixed now as well.

This is all work in progress, so I am very open to feedback.
